apiVersion: v1
kind: ConfigMap
metadata:
  name: ire-config
  namespace: ire-production
data:
  PROJECT_NAME: "Enterprise Platform (IRE)"
  POSTGRES_SERVER: "ire-postgres.internal"
  POSTGRES_DB: "ire_production_db"
  REDIS_HOST: "ire-redis.internal"
  CELERY_BROKER_URL: "redis://ire-redis.internal:6379/0"

---
apiVersion: v1
kind: Secret
metadata:
  name: ire-secrets
  namespace: ire-production
type: Opaque
stringData:
  SECRET_KEY: "PROD_SUPER_SECRET_KEY_32_BYTES_STRICT_SECURITY"
  POSTGRES_USER: "ire_admin"
  POSTGRES_PASSWORD: "ire_password_production_secure_2026"
